# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set a non-root user for security (optional but recommended)
RUN addgroup --system spring && adduser --system --ingroup spring springuser

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged JAR file into the container
# Make sure the JAR name matches the one generated by your build process
COPY target/spring-boot-todo-application.jar app.jar

# Change ownership of the files to the non-root user
RUN chown -R springuser:spring /app

# Switch to the non-root user
USER springuser

# Expose the port that the application runs on
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]

# Optional: Add a health check to ensure the container is running properly
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \
  CMD curl -f http://localhost:8080/actuator/health || exit 1
